name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run code analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and start Docker containers
        run: docker-compose up -d

      - name: Run PHPUnit
        run: docker-compose run php ./vendor/bin/phpunit --testdox
