name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run code analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and start Docker containers
        run: docker-compose up -d --scale phpunit=0

      - name: Install Composer dependencies
        run: composer install

      - name: Run PHPUnit
        run: php7.4 ./vendor/bin/phpunit --testdox
