name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run code analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Docker containers and run PHPUnit
        run: |
          docker-compose up -d
          docker-compose run php ./vendor/bin/phpunit --testdox
