name: Build
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run code analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create and start Docker containers
        run: docker-compose up -d --scale phpunit=0

      - name: Install Composer dependencies
        uses: php-actions/composer@v5

      - name: Run PHPUnit
        uses: php-actions/phpunit@v9
